### ISSUE TITLE
MSBuildGitHashCommand causes build to fail if there is no .git folder

### ISSUE THREAD

**Issue by rollsch** [MarkPflug/MSBuildGitHash#14]
Is it possible to ignore a missing .git folder and include a dummy value?

Sometimes we download old commits of our software to quickly test items out and the build will obviously fail due to there being no git repo. This is not immediately obvious to some of our team members.

Or alternatively just make it a warning?

Thanks

**Comment by MarkPflug** [comment]
Hello @rolandh. I've added the ability to handle a missing .git folder in the 1.0.0 release, which I just pushed to nuget. You must set the `MSBuildGitHashValidateSuccess` property to false to suppress the error. It will still show up as a warning though.

As for "downloading old commits", this won't exactly fix those, because they will be pointing to the older version of the nuget package where this doesn't exist. A potential workaround though, would be to specify the `MSBuildGitHashCommand` to `echo NoRepo`. You could do this from the command line to MSBuild with `'/p:MSBuildGitHashCommand=echo NoRepo'`. This "NoRepo" string will fail validation, so you can disable validation as well with `/p:MSBuildGitHashValidate=false` You should be able to set these as environment variables instead if that makes more sense for a particular environment. You can use whatever you want for the "NoRepo" string, it will be embedded in the assembly wherever the hash would normally appear.

Let me know if this fixes the issue for you. 

@gregbair Were you looking for a fix for this as well?

**Comment by rollsch** [comment]
@MarkPflug as long as going forward any new "old" commits wont have this problem as we will set it up to use the new nuget package that is a good improvement.

Thank for adding this, I will test it out today.

**Comment by MarkPflug** [comment]
I'm assuming this is working for you. If not, feel free to open a new issue.
