### ISSUE TITLE
Thoughts on Adding Commit Hash Always and a Data Class

### ISSUE THREAD

**Issue by drdamour** [MarkPflug/MSBuildGitHash#20]
hi, we're currently using this, but a couple of use cases came up and wanted to see if you think these would fit in your vision or if it's better for us to fork.

1. We have a need to ALWAYS have BOTH the commit hash & the output of  `git describe --tag` (which generally is a tag).  Are you open to adding a 2nd overridable command that ends up with metadata name GitDescribe ?
2. We need to read this data across all .net apps, so want to include a simple util class that does the reflection code in it's constructor (or some factory like pattern) to expose the meta values created by this build process (namely GitHash and GitDescribe).  I know this package has no classes today, so this would be a change.

if these do align, we can get a PR going.  let me know your thoughts.

**Comment by MarkPflug** [comment]
Hello,
Currently this package doesn't add any runtime dependency to projects that consume it, and that is very intentional. Now, there  is no reason you couldn't continue to use MSBuildGitHash to inject the values into your project, and create a separate package to allow accessing them at runtime, but I won't accept a PR that would add a runtime dependency to this project.

I would be very open to discussing adding `git describe --tag` output, however. How did you envision this being done? Adding it to the AssemblyInformationalVersion, or a different custom AssemblyMetadata attribute? I've never used git tags before, so I don't have much insight here.

**Comment by drdamour** [comment]
Thinking AssemblyMetadata

**Comment by drdamour** [comment]
there's quite a few git meta data attributes taht could be added over time, comign from javaland we mostly use https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/maven/docs/using-the-plugin-in-more-depth.md .  i just only happen to care about that tag tree info

**Comment by MarkPflug** [comment]
@drdamour A new version of the package has been pushed, 2.0.0-B0001 (prerelease), that contains this enhancement. If you can give a try and let me know if it looks suitable, I'll make it an official 2.0 release.

**Comment by MarkPflug** [comment]
Just pushed 2.0 release package to nuget.
