### ISSUE TITLE
Adding an annotated tag causes build error

### ISSUE THREAD

**Issue by sashoalm** [MarkPflug/MSBuildGitHash#6]
I managed to reproduce the problem in a new project by adding a one-letter annotated tag:
git tag -a B

I got the error:
MSBuildGitHash hash value starting with 'B-0-g91456ff' was invalid.

**Comment by MarkPflug** [comment]
This is a validation error. You can turn off validation by adding this property to your csproj:

`<MSBuildGitHashValidate>False</MSBuildGitHashValidate>`

I only added that validation, because I was worried if the command output was something like 'Failed to perform operation' it would detect it as an invalid value. You can also customize the regex that is used to validate. The default is this:


`<MSBuildGitHashValidateRegex>^[0-9A-Fa-f]{4,32}(-dirty|-broken)%3F%24</MSBuildGitHashValidateRegex>`
